config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :microposts, only: [:create, :destroy]
  resources :sessions, only: :create
  resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
    belongs_to :user
    validates :content, presence: true, length: { maximum: 250 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User" 
    # これは中間テーブルを作るやつ
    # follower, followed は user.rb で使われている。User 同士を結び受けるため(中間テーブル)、分かりやすくするために自分でつけた名前。
end

app/models/user.rb
class User < ApplicationRecord
    has_many :microposts
    has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
    has_many :passive_relationships, class_name:  "Relationship",
                                  foreign_key: "followed_id",
                                  dependent:   :destroy
    # ↑中間テーブルをたくさん持っている
    has_many :following, through: :active_relationships, source: :followed
    has_many :followers, through: :passive_relationships, source: :follower
    # ↑中間テーブルを通してたくさんのフォロー・フォロワーを持っている
    # ここの following, followers は @user.following.count として _user_info.html.erb で使われている。フォローしている・されているユーザー全部の情報が入っている
    # followed, follower は relationship.rb にある
    # ここの active_relationships, passive_relationships は下の関数と関係ない


    before_save { email.downcase! }
    # REGEX = Regular expression
    # To validate correct email structure
    EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

    validates :name, presence: true, length: { maximum: 50 }
    validates :email, presence: true, length: { maximum: 225 },
                format: { with: EMAIL_REGEX },
                uniqueness: { case_sensitive: false }

    has_secure_password
    validates :password, length: { minimum: 6 }, allow_nil: true

    def follow(other_user)
        Relationship.create(follower_id: id, followed_id: other_user.id)
    end
    # @user.follow でアクセスできる
    # current.user で来てるので id だけでいい

    def active_relationships
        Relationship.where(follower_id: id)
    end
    # する
    
    def passive_relationships
        Relationship.where(followed_id: id)
    end
    # される

    def relationship(other_user)
        active_relationships.find_by(followed_id: other_user.id)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
    def create 
        @micropost = current_user.microposts.new(micropost_params)

        if @micropost.save 
            redirect_to root_url
        else
            render "users/home_feed"
            # ↑今のページ
        end
    end

    def destroy 
       @micropost = Micropost.find(params[:id])
       @micropost.destroy
       
       redirect_to root_url
    end
    private
        def micropost_params
            params.require(:micropost).permit(:content)
        end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    def create
        other_user = User.find(params[:followed_id])
        current_user.follow(other_user)

        redirect_to user_url(other_user)
    end
    
    def destroy 
        relationship = Relationship.find(params[:id])
        other_user = User.find(relationship.followed_id)
        relationship.destroy

        redirect_to user_url(other_user)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create 
    @user = User.find_by(email: params[:session][:email])

    if @user && @user.authenticate(params[:session][:password])
      log_in(@user)
      flash[:success] = "Successfully logged in."
      redirect_to user_url(@user)
    else
      flash.now[:danger] = "Invalid Credentials."
      render 'new'
    end
  end

  def destroy 
    log_out
    flash[:info] = "Successfully logged out."

    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost = Micropost.new
      @microposts = current_user.microposts.paginate(page: params[:page], per_page: 5).order(created_at: "DESC")
      render "users/home_feed"
    end
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show 
        @user = User.find(params[:id])
        @microposts = @user.microposts.paginate(page: params[:page], per_page: 5)
        # current_user はログインしている自分のアカウント
        # @user はクリックして得た他のアカウントの情報
    end

    def new
        @user = User.new
    end
    
    def create 
        @user = User.new(user_params)

        if @user.save 
            redirect_to root_url
        else
            render "new"
        end
    end

    def edit 
        @user = User.find(params[:id])
    end

    def update 
        @user = User.find(params[:id])
    
        if @user.update(user_params)
            redirect_to user_url(@user)
        else
          render "edit"
        end
    end

    def index 
        @users = User.paginate(page: params[:page], per_page: 10)
    end

    private
        def user_params
            params.require(:user).permit(:name, :email, :password, :password_confirmation)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        # この user には入力したユーザーの情報が全部入っている

        session[:user_id] = user.id
        # user.id は id(数字) のみで、これを session[:user_id](サーバー上)に保存する
    end

    def current_user
        User.find_by(id: session[:user_id])
        # User(テーブル上) の id と、session[:user_id](サーバー上) の id を比べて、同じなら current_user にその行の情報を保存する
    end

    def logged_in?
        !current_user.nil?
    end
    # ヘッダーのif文で使う
    # 「空ですか？」 よりも、「ありますか？」　の方がいい

    def log_out
        session.delete(:user_id)
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"

        image_tag(gravatar_url, alt: user.name)
    end
end

app/views/layouts/_footer.html.erb
<hr>
<footer class="container">
    <div class="footer_item">
        <p>AwesomeBlog application ©️ Tsugumi Kanezaki</p>
    </div>
    
    <div class="footer_right">
        <div class="footer_item">
            <%= link_to "Home", root_path, class:"nav-item text-black-50" %>
        </div>
        <div class="footer_item">
            <%= link_to "About", about_path, class:"nav-item text-black-50" %>
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <a class="navbar-brand" href="#">AwesomeBlog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <%# <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a> %>
        <%= link_to "Home", root_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%# <a class="nav-link" href="#">About</a> %>
        <%= link_to "About", about_path, class:"nav-link" %>
      </li>
      
      <% if logged_in? %>
        <li class="nav-item">
          <%= link_to "Users", users_url(current_user), class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to current_user.name, current_user, class:"nav-link" %>
        </li>
        <li>
          <%= link_to "Edit", edit_user_path(current_user), class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", logout_path, method: :delete, class:"nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%# <a class="nav-link" href="#">Sign-up</a> %>
          <%= link_to "Sign up", signup_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%# <a class="nav-link" href="#">Sign-in</a> %>
          <%= link_to "Log in", login_path, class:"nav-link" %>
        </li>
      <% end %>
    </ul>
    <%# <form class="form-inline mt-2 mt-md-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Awesomeblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>

    <div class="container p-3">
      <% if flash.any? %>
        <% flash.each do |type, msg| %>
          <div class="alert alert-<%= type %>">
            <div><%= msg %></div>
          </div>
        <% end %>
      <% end %>
          
      <%= yield %>
    </div>

    <%= render "layouts/footer" %>
  </body>
</html>

app/views/microposts/_micropost.html.erb
<li class="media mb-4">
    <div class="mr-2">
        <%= link_to gravatar_for(micropost.user), user_url(micropost.user) %>
    </div>

    <div class="media-body">
        <h5><%= link_to micropost.user.name, micropost.user %></h5>
        <div><%= micropost.content %></div>

        <small class="text-muted">Posted <%= time_ago_in_words(micropost.created_at) %> ago</small>
    </div>

    <% if micropost.user == current_user %>
        <%= link_to micropost_url(micropost), method: :delete,
                    data: { confirm: "Are you sure?" },
                    class: "float-right" do %>
            <i class="fa fa-times text-muted"></i>    
        <% end %>
        <%# link の中にものがあるから do と end が必要 %>
    <% end %>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>

    <div class="alert alert-danger">
        <p>
            The form contains <%= pluralize(object.errors.count, "error") %>
        </p>

        <ul>
            <% object.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
 
<% end %>

app/views/static_pages/about.html.erb
<main role="main" class="container">
  <div class="jumbotron">
    <h1>About AwesomeBlog!</h1>
    <p>This is a Ruby on Rails application. A project by <strong>Kredo PH</strong> and <strong>Framgia PH</strong></p>
  </div>
</main>

app/views/static_pages/home.html.erb
<main role="main" class="container">
  <div class="jumbotron">
    <h1>AwesomeBlog app</h1>
    <h2>Welcome to awesomeblog!</h2>
  </div>
</main>

app/views/users/_form.html.erb
<%=  form_for(@user) do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <div class="form-group">
    <%= f.label :name %> <br>
    <%= f.text_field :name, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %> <br>
    <%= f.text_field :email, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password %> <br>
    <%= f.password_field :password, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %> <br>
    <%= f.password_field :password_confirmation, class:"form-control" %>
  </div>
  <%# <button type="submit" class="btn btn-primary btn-block">Submit</button> %>
  <%= f.submit btn_msg, class:"btn btn-primary btn-block" %>
<% end %>

app/views/users/_user_info.html.erb
<div class="jumbotron">
    <div class="row">
        <div class="col-md-8">
            <div class="media">
                <%= gravatar_for @user %>

                <div class="media-body ml-3">
                    <h1><%= @user.name %></h1>
                    <p><%= @user.email %></p>

                    <% if current_user != @user %>
                        <% unless current_user.relationship(@user) %>
                            <%= button_to "Follow",
                                relationships_path,
                                params: { followed_id: @user.id },
                                class: "btn btn-sm btn-success" %>
                        <% else %>
                            <%= button_to "Unfollow",
                                relationship_path(current_user.relationship(@user)),
                                method: :delete,
                                class: "btn btn-sm btn-danger" %>
                        <% end %>
                    <% end %>
                </div>
            </div>
        </div>
        <div class="col-md-4 text-center">
            <div class="row">
                <div class="col">
                    <h3><%= link_to @user.microposts.count, @user %></h3>
                    microposts
                </div>
                <div class="col">
                    <h3><%= @user.following.count %></h3>
                    following
                </div>
                <div class="col">
                    <h3><%= @user.followers.count %></h3>
                    followers
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<div class="col-sm-6 mx-auto">
    <h1 class="text-center">Edit</h1>
    <hr>
    <%= render "form", btn_msg: "Edit account" %>
</div>

app/views/users/home_feed.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="card-deck">
                <div class="card">
                    <div class="p-4">
                        <div class="text-center">
                            <%= gravatar_for(current_user) %>
                        </div>
                        <div class="card-body text-center border-bottom">
                            <h2 class="card-title"><%= current_user.name %></h2>
                            <p class="card-text"><%= current_user.email %></p>
                        </div>

                        <div class="mt-3">
                            <div class="row">
                                <h5 class="col-md-4 text-center">
                                    <%= link_to current_user.microposts.count, @user %>
                                </h5>
                                <h5 class="col-md-4 text-center">
                                    <%= current_user.following.count %>
                                </h5>
                                <h5 class="col-md-4 text-center">
                                    <%= current_user.followers.count %>
                                </h5>
                            </div>
                            <div class="row">
                                <small class="col-md-4 text-center">microposts</small>
                                <small class="col-md-4 text-center">following</small>
                                <small class="col-md-4 text-center">followers</small>
                            </div>
                        </div>
                    </div>

                    <div class="card-footer">
                        <%=  form_for(@micropost) do |f| %>
                            <%= render "shared/error_messages", object: f.object %>
                            <div class="form-group">
                                <%= f.text_area :content, class: "form-control", placeholder:"Share your thought…" %>
                            </div>
                            <div class="mt-3">
                                <%= f.submit "Post", class: "btn btn-primary btn-block" %>
                            </div>
                        <% end %>
                        
                        <%# <textarea class="form-control mb-3" rows="2" placeholder="Share your thought…"></textarea>
                        <button type="submit" class="btn btn-primary btn-block">Post</button> %>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <h2>Feed</h2>
                    <hr>

                    <% if @microposts.any? %>
                        <ul class="list-unstyled">
                            <%= render @microposts %>
                            <%# 違う使い方 %>
                        </ul>
                    <% else %>
                        <div class="text-muted">
                            <p>Nothing to show</p>
                        </div>
                    <% end %>
                </div>

                <div class="card-footer paginate text-center">
                    <%= will_paginate @microposts if @microposts.any? %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<div class="container">
    <h1 class="text-center">Users</h1>
    <hr>

    <div class="paginate text-center">
        <%= will_paginate %>
    </div>

    <div class="row">
        <% @users.each do |user| %>
            <div class="col-md-6">
                <div class="media pb-3">
                    <%= gravatar_for(user) %>
                    <div class="media-body ml-3">
                        <%# <h5 class="mt-0">user.name</h5> %>
                        <%= link_to user.name, user%>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

<div class="paginate text-center border-top pt-3">
    <%= will_paginate %>
</div>

app/views/users/new.html.erb
<div class="col-sm-6 mx-auto">
    <h1 class="text-center">Sign Up</h1>
    <hr>
    <%= render "form", btn_msg: "Create a new account" %>
</div>

app/views/users/show.html.erb
<%= render "users/user_info" %>

<div>
    <% if @microposts.any? %>
        <!-- rendering a collection: micropost/_micropost.html.erb -->
        <ul class="list-unstyled">
            <%= render @microposts %>
        </ul>
    <% else %>
        <div class="text-muted">Nothing to show</div>
    <% end %>
</div>
<hr>
<div class="card-footer paginate text-center">
    <%= will_paginate @microposts if @microposts.any? %>
</div>